apiVersion: v1
kind: Service
metadata:
  name: formation-video
  namespace: formation-lap
spec:
  selector:
    app: formation-video
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

