apiVersion: v1
kind: Service
metadata:
  name: formation-search
  namespace: formation-lap
spec:
  selector:
    app: formation-search
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

